services:
  api:
    build:
        context: .
        dockerfile: ./docker/local/django/Dockerfile
    command: /start
    container_name: django_api
    volumes:
        - .:/app
        - static_volumes:/app/staticfile
        - media_volumes:/app/mediafiles
    ports:
        - "8000:8000"
    env_file:
        - ./.envs/.local/.django
        - ./.envs/.local/.postgres
    depends_on:
        - postgres
        - mailhog
    networks:
        - authors-api-live
  
  postgres:
    build:
        context: .
        dockerfile: ./docker/local/postgres/Dockerfile
    volumes:
        - local_posggres_data:/var/lib/postgresql/data
        - local_postgres_data_backups:/backups
    env_file:
        - ./.envs/.local/.postgres
    environment:
      - POSTGRES_DB="${POSTGRES_DB}"
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
    networks:
        - authors-api-live
  
  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
        - "8025:8025"
    networks:
        - authors-api-live

networks:
  authors-api-live:
    driver: bridge

volumes:
  local_posggres_data: {}
  local_postgres_data_backups: {}
  static_volumes:
  media_volumes: